openapi: 3.0.1
info:
  title: TFT DB Service
  description: Teamfight tactics database service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
paths:
  '/riotApi':
    get:
      summary: Make riot api request or use cached result 
      operationId: riotApi
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
            format: uri
        - name: force
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: 200 OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 400 Bad Request
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 500 Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  '/matchHistory':
    get:
      summary: Get match history for a single summoner
      operationId: matchHistory
      parameters:
        - name: puuid
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 400 Bad Request
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 500 Internal Server Error
          content:
            text/plain:
              schema:
                type: string
