openapi: 3.0.1
info:
  description: Teamfight tactics database service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: TFT DB Service
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
paths:
  /riotApi:
    get:
      operationId: riotApi
      parameters:
      - explode: true
        in: query
        name: url
        required: true
        schema:
          format: uri
          type: string
        style: form
      - explode: true
        in: query
        name: force
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: 200 OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: 400 Bad Request
        "500":
          content:
            text/plain:
              schema:
                type: string
          description: 500 Internal Server Error
      summary: Make riot api request or use cached result
  /matchHistory:
    get:
      operationId: matchHistory
      parameters:
      - explode: true
        in: query
        name: puuid
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: 200 OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: 400 Bad Request
        "500":
          content:
            text/plain:
              schema:
                type: string
          description: 500 Internal Server Error
      summary: Get match history for a single summoner
components:
  schemas: {}

